# Generated by Django 5.1.4 on 2024-12-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.CharField(max_length=255, unique=True)),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_objetivo', models.CharField(max_length=255)),
                ('id_curso', models.TextField()),
                ('nombre', models.TextField()),
                ('objetivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RALink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.TextField()),
                ('id_objetivo', models.TextField()),
                ('importancia', models.TextField()),
                ('id_prerequisito', models.TextField()),
                ('id_objetivo_prerequisito', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_curso', models.CharField(max_length=255)),
                ('id_requisito', models.TextField()),
            ],
        ),
    ]
